---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: weighted-whoami
spec:
  weighted:
    services:
      - name: whoamiv1
        port: 80
        weight: 3
      - name: whoamiv2
        port: 80
        weight: 1
        